version: '3.2'
services:

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: eipp
      MYSQL_ROOT_PASSWORD: 1qazZAQ!
    ports:
      - 3306

  php:
    build: ./phpfpm
    volumes:
      - ./web/:/var/www/html
    ports:
      - 9000
    environment:
      DB_HOST: db
      DB_DATABASE: eipp
      DB_USERNAME: root
      DB_PASSWORD: 1qazZAQ!
      DB_PORT: 3306

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./web/:/var/www/html
    ports:
      - 80:80